Ext.define('symhelp.store.symptomsStore',{
	requires : ['symhelp.model.symptoms',
		    'Ext.data.proxy.Rest'],
	extend : 'Ext.data.Store',
	config : {
		model : 'symhelp.model.symptoms',
		storeId : 'symptomsStore',
		data: [
		{symptom: 'Null',  value: 0},
                {symptom: 'Abdominal Pain',  value: 79},
                {symptom: 'Agitation', value: 32},
                {symptom: 'Angina Pectoris', value: 9},
                {symptom: 'Asthenia',  value: 4},
                {symptom: 'Blackout',  value: 29},
                {symptom: 'Bradycardia',  value: 60},
                {symptom: 'Breath sounds decreased',  value: 44},
                {symptom: 'Breech Presentation',  value: 74},
                {symptom: 'Cardovascular Finding/Event', value: 80},
                {symptom: 'Chest Discomfort',  value: 59},
                {symptom: 'Chest Pain',  value: 1},
                {symptom: 'Chest Tightness', value: 38},
                {symptom: 'Chill',  value: 43},
                {symptom: 'Cough',  value: 40},
                {symptom: 'Difficulty passing urine', value: 68},
                {symptom: 'Distress Respiratory', value: 51},
                {symptom: 'Dizziness',  value: 3},
                {symptom: 'Dyspnea on Exertion',  value: 39},
                {symptom: 'Dysuria',  value: 69},
                {symptom: 'Energy Increased', value: 35},
                {symptom: 'Facial Paresis', value: 55},
                {symptom: 'Fall', value: 5},
                {symptom: 'Fatigue',  value: 62},
                {symptom: 'Feeling Hopeless',  value: 24},
                {symptom: 'Feeling Suicidal', value: 22},
                {symptom: 'Fever', value: 41},
                {symptom: 'Flatulence',  value: 72},
                {symptom: 'Frail',  value: 71},
                {symptom: 'Green Sputum', value: 45},
                {symptom: 'Haemotysis',  value: 49},
                {symptom: 'Hallucinations',  value: 23},
                {symptom: 'Hemiplegia',  value: 56},
                {symptom: 'Homelessness',  value: 37},
                {symptom: 'Immobile',  value: 76},
                {symptom: 'Intoxication',  value: 34},
                {symptom: 'Irritable Mood', value: 28},
                {symptom: 'Labored Breathing',  value: 17},
                {symptom: 'Left Atrial Hypertrophy', value: 77},
                {symptom: 'Lethargy',  value: 67},
                {symptom: 'Lung Nodule', value: 73},
                {symptom: 'Malaise',  value: 47},
                {symptom: 'Mental status change', value: 18},
                {symptom: 'Mood Depressed',  value: 30},
                {symptom: 'Motor Retardation',  value: 27},
                {symptom: 'Nausea',  value: 8},
                {symptom: 'Nightmare',  value: 36},
                {symptom: 'Night Sweat',  value: 46},
                {symptom: 'Numbness', value: 58},
                {symptom: 'Orthopnea',  value: 21},
                {symptom: 'Orthostasis', value: 65},
                {symptom: 'Pain',  value: 64},
                {symptom: 'Palpitaion',  value: 10},
                {symptom: 'Pleuritic Pain',  value: 53},
                {symptom: 'Polydypsia',  value: 14},
                {symptom: 'Polyuria', value: 15},
                {symptom: 'Pressure Chest',  value: 7},
                {symptom: 'Rale',  value: 20},
                {symptom: 'Renal Angle Tenderness',  value: 66},
                {symptom: 'Scar Tissue',  value: 78},
                {symptom: 'Shortness of Breath', value: 2}, 
                {symptom: 'Sleeplessness',  value: 26},
                {symptom: 'Speech Slurred',  value: 54},
                {symptom: 'Sweat',  value: 11}, 
                {symptom: 'Sweating Increased', value: 12},
                {symptom: 'Swelling', value: 61},
                {symptom: 'Syncope',  value: 6},
                {symptom: 'Systolic Murmur', value: 70},
                {symptom: 'Tachypnea',  value: 50},
                {symptom: 'Tremor',  value: 33},
                {symptom: 'Tumor cell invasion',  value: 63},
                {symptom: 'Unresponsiveness',  value: 19},
                {symptom: 'Vertigo',  value: 13},
                {symptom: 'Vomiting',  value: 16},
                {symptom: 'Weepiness', value: 25},
                {symptom: 'Weight Loss',  value: 75},
                {symptom: 'Wheezing', value: 48},
                {symptom: 'Worry',  value: 31},
                {symptom: 'Yellow Sputum',  value: 42}
		]
	}
});